language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

# command to install dependencies
install:
  - pip install pylint
  - pip install .

# command to run tests
script: 
  - pylint --disable=R0904 rpn_calculator/ test/ setup.py get_commands.py
  - python -m unittest
 
