name: rpn calculator

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint --extension-pkg-whitelist=PyQt5 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n calculator/ setup.py
    - name: Test with unittest
      run: |
        python -m unittest
    - name: Install
      run: |
        python setup.py install
